services:
  anvil:
    image: registry.cn-shenzhen.aliyuncs.com/wl4g/foundry_anvil:1.7.1
    ports: ["8545:8545"]
    command:
      - --host=0.0.0.0
      - --port=8545
      - --accounts=10
      - --balance=10000
      - --chain-id=31337
    healthcheck:
      test: ["CMD", "curl", "-sf", "-X", "POST", "-H", "Content-Type: application/json", "-d", '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}', "http://localhost:8545"]
      interval: 5s
      timeout: 3s
      retries: 12
