{{- $ext := .Values.envoy_gateway.ext_authz -}}
{{- $jwt := $ext.jwt -}}
{{- if and $ext.enabled $jwt.enabled (not $jwt.remoteJWKS.uri) (not $jwt.localJWKS.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authguard.jwtJwksConfigMapName" . }}
  labels:
    {{- include "authguard.labels" . | nindent 4 }}
data:
  jwks: {{ required "envoy_gateway.ext_authz.jwt.localJWKS.inline is required when remoteJWKS.uri and existingConfigMap are empty" $jwt.localJWKS.inline | quote }}
{{- end }}
