{{- if .Values.authguard.authz.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authguard.fullname" . }}
  labels:
    {{- include "authguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: authz
spec:
  type: ClusterIP
  selector:
    {{- include "authguard.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: authz-grpc
      port: {{ .Values.authguard.authz.service.grpcPort }}
      targetPort: authz-grpc
      appProtocol: grpc
    - name: scope-grpc
      port: {{ .Values.authguard.authz.service.scopeGrpcPort }}
      targetPort: scope-grpc
      appProtocol: grpc
    {{- if .Values.authguard.authz.mgmt.enabled }}
    - name: mgmt
      port: {{ .Values.authguard.authz.service.mgmtPort }}
      targetPort: mgmt
    {{- end }}
{{- end }}
