apiVersion: v2
name: authguard
description: Envoy Gateway integrated authentication and authorization platform
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: gateway-helm
    alias: envoy_gateway
    version: v1.9.0
    repository: oci://docker.io/envoyproxy
    condition: envoy_gateway.enabled
  - name: redis-cluster
    alias: redis_cluster
    version: 8.8.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis_cluster.enabled
