{{- if .Values.support.enabled }}
{{- $authguard := index .Values "authguard-middleware" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-growth-e2e.accessContextSecretName" . }}
  labels:
    {{- include "customer-growth-e2e.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $authguard.accessContext.key }}: {{ required "authguard-middleware.accessContext.signingKey is required" $authguard.accessContext.signingKey | quote }}
{{- end }}
