apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-growth-e2e.accessContextSecretName" . }}
  labels:
    {{- include "customer-growth-e2e.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authguard.accessContext.key }}: {{ required "authguard.accessContext.signingKey is required" .Values.authguard.accessContext.signingKey | quote }}
