{{- if .Values.authguard.authz.serviceAccount.create }}
{{- $annotations := merge (deepCopy .Values.authguard.authz.serviceAccount.annotations) .Values.secrets.serviceAccount.annotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authguard.serviceAccountName" . }}
  labels:
    {{- include "authguard.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
