{{- $web := .Values.authguard.web -}}
{{- $globalThemeConfigMap := tpl (default "" .Values.global.authguard.themeConfigMap) . -}}
{{- $themeConfigMap := coalesce $web.theme.existingConfigMap $globalThemeConfigMap "" -}}
{{- if $web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authguard.fullname" . }}-web
  labels:
    {{- include "authguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ $web.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector:
    matchLabels:
      {{- include "authguard.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authguard.webSelectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with $web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: authguard-web
          image: "{{ $web.image.repository }}:{{ default .Chart.AppVersion $web.image.tag }}"
          imagePullPolicy: {{ $web.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          ports:
            - { name: http, containerPort: {{ $web.service.port }} }
          livenessProbe:
            httpGet: { path: /, port: http }
          readinessProbe:
            httpGet: { path: /, port: http }
          resources:
            {{- toYaml $web.resources | nindent 12 }}
          volumeMounts:
            - { name: tmp, mountPath: /tmp }
            - { name: nginx-cache, mountPath: /var/cache/nginx }
            {{- if $themeConfigMap }}
            - { name: custom-themes, mountPath: /usr/share/nginx/html/assets/themes/custom, readOnly: true }
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        {{- if $themeConfigMap }}
        - name: custom-themes
          configMap:
            name: {{ $themeConfigMap }}
        {{- end }}
{{- end }}
